#remote_theme: pages-themes/midnight@v0.2.0
# https://github.com/cotes2020/jekyll-theme-chirpy/
remote_theme: cotes2020/jekyll-theme-chirpy/
plugins:
- jekyll-remote-theme
# theme: jekyll-chirpy
title: BaptMania's homepage
description: Bookmark this to keep an eye on my project updates!
